/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package org.tguduru.avro.schema;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum ProductType { 
  Electronics, Books, Home, Tools, Sports, Music, Auto, Grocery  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"ProductType\",\"namespace\":\"org.tguduru.avro.schema\",\"symbols\":[\"Electronics\",\"Books\",\"Home\",\"Tools\",\"Sports\",\"Music\",\"Auto\",\"Grocery\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
